In [21]:
import numpy as np
import matplotlib.pyplot as plt


A = np.array([
    [0.582745, 0.48    , 0.10    , 0.      , 0.      ],
    [0.48    , 1.044129, 0.46    , 0.10    , 0.      ],
    [0.10    , 0.46    , 1.10431 , 0.44    , 0.10    ],
    [0.      , 0.10    , 0.44    , 0.963889, 0.42    ],
    [0.      , 0.      , 0.10    , 0.42    , 0.522565]
])


b = np.array([1.162745, 2.084129, 2.20431, 1.923889, 1.042565])

tol = np.array([10**-2])



def Jacobi(A, b, tol, xs_by_tol, errors_by_tol, max_iter=100000):

    if b.ndim == 2 and b.shape[1] == 1:
        b = b[:, 0]

    for k in range(tol.shape[0]):

        isConverged = False
        x = np.zeros(A.shape[0])     
        errors = []
        xs = [x.copy()]
        it = 0

        while (not isConverged) and it < max_iter:
            x_update = np.zeros(A.shape[0])
            ATermsArray = np.zeros(A.shape[0])

            for i in range(A.shape[0]):

                for j in range(A.shape[1]):
                    if (i == j):
                        continue

                    ATermsArray[i] += A[i][j] * (x[j])

                x_update[i] = (b[i] - ATermsArray[i]) / A[i][i]

            changes = np.zeros(A.shape[0])
            for i in range(A.shape[0]):
                changes[i] = x_update[i] - x[i]

            err = np.max(np.abs(changes))
            if err < tol[k]:
                isConverged = True

            errors.append(err)
            x = x_update
            xs.append(x.copy())
            it += 1

        if not isConverged:
            raise RuntimeError(f"Jacobi did not converge within max_iter={max_iter} for tol={tol[k]}")

        errors_by_tol.append(errors)
        xs_by_tol.append(xs)

    return xs_by_tol, errors_by_tol


def GaussSeidel(A, b, tol, xs_by_tol, errors_by_tol, max_iter=100000):
    # make b 1-D so b[i] works like your original code
    if b.ndim == 2 and b.shape[1] == 1:
        b = b[:, 0]

    for k in range(tol.shape[0]):

        isConverged = False
        x = np.zeros(A.shape[0])     # 1-D like your original
        errors = []
        xs = [x.copy()]
        it = 0

        while (not isConverged) and it < max_iter:
            x_update = np.zeros(A.shape[0])
            ATermsArray = np.zeros(A.shape[0])

            for i in range(A.shape[0]):

                for j in range(A.shape[1]):
                    if (i == j):
                        continue
                    if (j < i):
                        ATermsArray[i] += A[i][j] * (x_update[j])
                    else:
                        ATermsArray[i] += A[i][j] * (x[j])

                x_update[i] = (b[i] - ATermsArray[i]) / A[i][i]

            changes = np.zeros(A.shape[0])
            for i in range(A.shape[0]):
                changes[i] = x_update[i] - x[i]

            err = np.max(np.abs(changes))
            if err < tol[k]:
                isConverged = True

            errors.append(err)
            x = x_update
            xs.append(x.copy())
            it += 1

        if not isConverged:
            raise RuntimeError(f"Gauss-Seidel did not converge within max_iter={max_iter} for tol={tol[k]}")

        errors_by_tol.append(errors)
        xs_by_tol.append(xs)

    return xs_by_tol, errors_by_tol



jacobi_xs = []
jacobi_errors = []
gs_xs = []
gs_errors = []

jacobi_xs, jacobi_errors = Jacobi(A, b, tol, jacobi_xs, jacobi_errors)
gs_xs, gs_errors = GaussSeidel(A, b, tol, gs_xs, gs_errors)


A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1])

jacobi_xs2, jacobi_errors2 = Jacobi(A, b, tol, jacobi_xs, jacobi_errors)
gs_xs2, gs_errors2 = GaussSeidel(A, b, tol, gs_xs, gs_errors)


for k in range(tol.shape[0]):
    print("Challenge 1 \n")
    print(f"Jacobi tol={tol[k]:.0e}, iterations={len(jacobi_errors[k])}, x_final=\n{jacobi_xs[k][-1]}\n")
    print(f"Gauss-Seidel tol={tol[k]:.0e}, iterations={len(gs_errors[k])}, x_final=\n{gs_xs[k][-1]}\n")
    print("Challenge 2 \n")
    print(f"Jacobi tol={tol[k]:.0e}, iterations={len(jacobi_errors[k])}, x_final=\n{jacobi_xs[k][-1]}\n")
    print(f"Gauss-Seidel tol={tol[k]:.0e}, iterations={len(gs_errors[k])}, x_final=\n{gs_xs[k][-1]}\n")
    

    
    
    


Challenge 1 

Jacobi tol=1e-02, iterations=1265, x_final=
[1.00498443 1.00498702 1.00498737 1.00498599 1.00498261]

Gauss-Seidel tol=1e-02, iterations=7, x_final=
[0.99934155 1.00244106 0.99663098 1.00322643 0.99805153]

Challenge 2 

Jacobi tol=1e-02, iterations=1265, x_final=
[1.00498443 1.00498702 1.00498737 1.00498599 1.00498261]

Gauss-Seidel tol=1e-02, iterations=7, x_final=
[0.99934155 1.00244106 0.99663098 1.00322643 0.99805153]



True
