In [1]:
import numpy as np

def gaussian_elimination(A, b):
    # Make copies as float arrays so we don't modify the originals
    A = np.array(A, dtype=float).copy()
    b = np.array(b, dtype=float).copy()

    n = len(b)

    # Forward elimination (with partial pivoting)
    for i in range(n):
        # Pivoting: find row with largest absolute value in column i (from i..n-1)
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row].copy(), A[i].copy()
        b[i], b[max_row] = b[max_row], b[i]

        # Optional: detect singular/near-singular pivot
        if abs(A[i][i]) < 1e-12:
            raise ValueError("Matrix is singular or nearly singular.")

        # Make rows below this one 0 in current column
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]

    # Backward substitution
    x = [0.0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]

    return x


A = np.array([
    [ 2,  1, -1],
    [-3, -1,  2],
    [-2,  1,  2]
], dtype=float)

b = np.array([8, -11, -3], dtype=float)

x = gaussian_elimination(A, b)
print("Solution x =", x)



Solution x = [2.0, 3.0000000000000004, -0.9999999999999999]


In [2]:
import numpy as np

def lu_decomposition(A):
    A = np.array(A, dtype=float)
    n = A.shape[0]

    L = np.eye(n)
    U = A.copy()                   

    for i in range(n):
        # check pivot
        if U[i, i] == 0:
            raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")

        # eliminate entries below pivot
        for j in range(i + 1, n):
            factor = U[j, i] / U[i, i]
            L[j, i] = factor
            for k in range(i, n):
                U[j, k] -= factor * U[i, k]

    return L, U



A = np.array([
    [ 2, 3,  1],
    [ 4, 7, -1],
    [-2, 1,  2]
], dtype=float)

L, U = lu_decomposition(A)

print("A:\n", A)
print("L:\n", L)
print("U:\n", U)
print("Check (L @ U):\n", L @ U)


A:
 [[ 2.  3.  1.]
 [ 4.  7. -1.]
 [-2.  1.  2.]]
L:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  4.  1.]]
U:
 [[ 2.  3.  1.]
 [ 0.  1. -3.]
 [ 0.  0. 15.]]
Check (L @ U):
 [[ 2.  3.  1.]
 [ 4.  7. -1.]
 [-2.  1.  2.]]


In [3]:
import numpy as np
from scipy.linalg import lu

A = np.array([
    [ 2, 3,  1],
    [ 4, 7, -1],
    [-2, 1,  2]
], dtype=float)

P, L, U = lu(A)

print("A:\n", A)
print("P:\n", P)
print("L:\n", L)
print("U:\n", U)
print("Check (P @ A):\n", P @ A)
print("Check (L @ U):\n", L @ U)


A:
 [[ 2.  3.  1.]
 [ 4.  7. -1.]
 [-2.  1.  2.]]
P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
L:
 [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.5        -0.11111111  1.        ]]
U:
 [[ 4.          7.         -1.        ]
 [ 0.          4.5         1.5       ]
 [ 0.          0.          1.66666667]]
Check (P @ A):
 [[-2.  1.  2.]
 [ 2.  3.  1.]
 [ 4.  7. -1.]]
Check (L @ U):
 [[ 4.  7. -1.]
 [-2.  1.  2.]
 [ 2.  3.  1.]]
